version: 0.2
env:
  shell: bash
phases:
  pre_build:
    commands:
      - pip3 uninstall -y awscli
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - aws ecr get-login-password | docker login -u AWS --password-stdin $IMAGE_REG
  build:
    on-failure: ABORT
    commands:
      - make deploy