AWSTemplateFormatVersion: '2010-09-09'
Description: Build pipeline for nodejs-demoapp

Resources:
  NodeJSDemo:
    Type: AWSSamples::CodePipeline::MultiarchECS::MODULE
    Properties:
      RepositoryId: otterley/nodejs-demoapp
      BranchName: master
      ImageRepositoryName: nodejs-demoapp
      CodeStarConnectionArn: arn:aws:codestar-connections:us-west-2:523443631803:connection/aafa4a94-2aed-40b0-a3bb-fc33d238a5f0
      BuildAndPushImageBuildspecPath: buildspec.yml
      BuildAndPushManifestBuildspecPath: buildspec-manifest.yml
      DeployBuildspecPath: buildspec-deploy.yml
